<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_XpwKgI5eEfCez5hyndgAQQ" name="Consejo directivo" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_XpwKgY5eEfCez5hyndgAQQ" name="Proceso de consejo directivo">
      <elements xmi:type="process:Lane" xmi:id="_XpwKgo5eEfCez5hyndgAQQ" name="Consejo directivo lane" actor="_xrmMsI5nEfCez5hyndgAQQ">
        <elements xmi:type="process:Task" xmi:id="_XpwKh45eEfCez5hyndgAQQ" name="Revisar ejecucion del proyecto" outgoing="_GMpe0I58EfCez5hyndgAQQ" incoming="_Zka54I5-EfCez5hyndgAQQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XpwKiI5eEfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XpwKiY5eEfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XpwKio5eEfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XpwKi45eEfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XpwKjI5eEfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XpwKjY5eEfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XpwKjo5eEfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XpwKj45eEfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_XpwKkI5eEfCez5hyndgAQQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_XpwKkY5eEfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_XpwKko5eEfCez5hyndgAQQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_XpwKk45eEfCez5hyndgAQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_EYVBgI58EfCez5hyndgAQQ" name="Cargar observaciones y mejoras" outgoing="_K_5LYI58EfCez5hyndgAQQ" incoming="_GMpe0I58EfCez5hyndgAQQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EYVBgo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EYVBgY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EYVBg458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EYVBhI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EYVBhY58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EYVBho58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EYVBiI58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EYVBh458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EYVBio58EfCez5hyndgAQQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_EYVBi458EfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EYVBiY58EfCez5hyndgAQQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EYVBjI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateThrowMessageEvent" xmi:id="_Iq5C4I58EfCez5hyndgAQQ" name="Enviar observaciones" outgoing="_Mkhm4I58EfCez5hyndgAQQ" incoming="_K_5LYI58EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Iq5C4o58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Iq5C4Y58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Iq5p8I58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_EnfQII6CEfCez5hyndgAQQ" name="throw_obs_start_obs">
            <correlation xmi:type="process:Correlation" xmi:id="_EnfQIY6CEfCez5hyndgAQQ">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_EnfQIo6CEfCez5hyndgAQQ"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_EnfQI46CEfCez5hyndgAQQ" name="Gestión del Proyecto - ONG Originante" content="Gestión del Proyecto - ONG Originante" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_EnfQJI6CEfCez5hyndgAQQ" name="Observación recibida" content="Observación recibida" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_EnfQJY6CEfCez5hyndgAQQ"/>
          </events>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Lo99kI58EfCez5hyndgAQQ" name="Fin de observaciones" incoming="_Mkhm4I58EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Lo-koY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Lo-koI58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Lo-koo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartTimerEvent" xmi:id="_VgzTcI5-EfCez5hyndgAQQ" name="15 dias" outgoing="_Zka54I5-EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VgzTco5-EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VgzTcY5-EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VgzTc45-EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_V8z6AI5-EfCez5hyndgAQQ" name="0 0 12 1/15 * ? *" content="0 0 12 1/15 * ? *"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_XpwKlI5eEfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_XpwKlY5eEfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_XpwKlo5eEfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_XpwKl45eEfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GMpe0I58EfCez5hyndgAQQ" target="_EYVBgI58EfCez5hyndgAQQ" source="_XpwKh45eEfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GMpe0Y58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GMpe0o58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_K_5LYI58EfCez5hyndgAQQ" target="_Iq5C4I58EfCez5hyndgAQQ" source="_EYVBgI58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_K_5LYY58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_K_5LYo58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Mkhm4I58EfCez5hyndgAQQ" target="_Lo99kI58EfCez5hyndgAQQ" source="_Iq5C4I58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Mkhm4Y58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Mkhm4o58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Zka54I5-EfCez5hyndgAQQ" target="_XpwKh45eEfCez5hyndgAQQ" source="_VgzTcI5-EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Zka54Y5-EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Zka54o5-EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_xrmMsI5nEfCez5hyndgAQQ" name="Consejo directivo" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_XpwKnI5eEfCez5hyndgAQQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XpwKnY5eEfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_XpwKno5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XpwKn45eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XpwKoI5eEfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_XpwKoY5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XpwKoo5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XpwKo45eEfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_XpwKpI5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XpwKpY5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XpwKpo5eEfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_XpwKp45eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XpwKqI5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_XpwKqY5eEfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_XpwKqo5eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_XpwKq45eEfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_XpwKrI5eEfCez5hyndgAQQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_XpwKrY5eEfCez5hyndgAQQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_XpwKro5eEfCez5hyndgAQQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_XpwKr45eEfCez5hyndgAQQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_XpwKsI5eEfCez5hyndgAQQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_XpwKsY5eEfCez5hyndgAQQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_XpwKso5eEfCez5hyndgAQQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_XpwKs45eEfCez5hyndgAQQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_XpwKtI5eEfCez5hyndgAQQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_XpwKtY5eEfCez5hyndgAQQ" type="Process" element="_XpwKgI5eEfCez5hyndgAQQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_XpwKto5eEfCez5hyndgAQQ" type="2007" element="_XpwKgY5eEfCez5hyndgAQQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_XpwKt45eEfCez5hyndgAQQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_XpwKuI5eEfCez5hyndgAQQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_XpwKuY5eEfCez5hyndgAQQ" type="3007" element="_XpwKgo5eEfCez5hyndgAQQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_XpwKuo5eEfCez5hyndgAQQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_XpwKu45eEfCez5hyndgAQQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_XpwKvI5eEfCez5hyndgAQQ" type="3005" element="_XpwKh45eEfCez5hyndgAQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XpwKvY5eEfCez5hyndgAQQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XpwKvo5eEfCez5hyndgAQQ" x="160" y="60" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EYVokI58EfCez5hyndgAQQ" type="3005" element="_EYVBgI58EfCez5hyndgAQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EYVoko58EfCez5hyndgAQQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EYVokY58EfCez5hyndgAQQ" x="374" y="66" width="145" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Iq5p8Y58EfCez5hyndgAQQ" type="3014" element="_Iq5C4I58EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Iq5p8458EfCez5hyndgAQQ" type="5030">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Iq5p9I58EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Iq5p8o58EfCez5hyndgAQQ" x="638" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Lo-ko458EfCez5hyndgAQQ" type="3003" element="_Lo99kI58EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Lo-kpY58EfCez5hyndgAQQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Lo-kpo58EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Lo-kpI58EfCez5hyndgAQQ" x="830" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Vg0hkI5-EfCez5hyndgAQQ" type="3016" element="_VgzTcI5-EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Vg0hko5-EfCez5hyndgAQQ" type="5031">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Vg0hk45-EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Vg0hkY5-EfCez5hyndgAQQ" x="62" y="82"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_XpwKw45eEfCez5hyndgAQQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_XpwKxI5eEfCez5hyndgAQQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_XpwKxY5eEfCez5hyndgAQQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_XpwKxo5eEfCez5hyndgAQQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XpwKx45eEfCez5hyndgAQQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_XpwKyI5eEfCez5hyndgAQQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_XpwKyY5eEfCez5hyndgAQQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_XpwKyo5eEfCez5hyndgAQQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_XpwKy45eEfCez5hyndgAQQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XpwKzI5eEfCez5hyndgAQQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_XpwKzY5eEfCez5hyndgAQQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_GMqF4I58EfCez5hyndgAQQ" type="4001" element="_GMpe0I58EfCez5hyndgAQQ" source="_XpwKvI5eEfCez5hyndgAQQ" target="_EYVokI58EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GMqF4458EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GMqF5I58EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GMqF4Y58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GMqF4o58EfCez5hyndgAQQ" points="[0, 2, -77, 0]$[68, 0, -9, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GMr7EI58EfCez5hyndgAQQ" id="(1.0,0.4246575342465753)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GMr7EY58EfCez5hyndgAQQ" id="(0.06206896551724138,0.375)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_K_5LY458EfCez5hyndgAQQ" type="4001" element="_K_5LYI58EfCez5hyndgAQQ" source="_EYVokI58EfCez5hyndgAQQ" target="_Iq5p8Y58EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_K_5LZo58EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_K_5LZ458EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_K_5LZI58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_K_5LZY58EfCez5hyndgAQQ" points="[0, 5, -86, -5]$[81, -5, -5, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_K_6ZgI58EfCez5hyndgAQQ" id="(1.0,0.3611111111111111)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Mkhm4458EfCez5hyndgAQQ" type="4001" element="_Mkhm4I58EfCez5hyndgAQQ" source="_Iq5p8Y58EfCez5hyndgAQQ" target="_Lo-ko458EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MkiN8I58EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MkiN8Y58EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Mkhm5I58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mkhm5Y58EfCez5hyndgAQQ" points="[-10, -1, -187, -8]$[175, 21, -2, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mki1AI58EfCez5hyndgAQQ" id="(1.0,0.9666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Zka5445-EfCez5hyndgAQQ" type="4001" element="_Zka54I5-EfCez5hyndgAQQ" source="_Vg0hkI5-EfCez5hyndgAQQ" target="_XpwKvI5eEfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Zkbg8o5-EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Zkbg845-EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Zkbg8I5-EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Zkbg8Y5-EfCez5hyndgAQQ" points="[-4, -3, -97, 0]$[68, 1, -25, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZkcvEI5-EfCez5hyndgAQQ" id="(1.0,0.9)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZkcvEY5-EfCez5hyndgAQQ" id="(0.17123287671232876,0.6301369863013698)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
