<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_5NtGsI58EfCez5hyndgAQQ" name="ONG originante y red de ONGs" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_5Qf8AI58EfCez5hyndgAQQ" name="Consejo directivo y ong originante">
      <elements xmi:type="process:Lane" xmi:id="_a4HL8I9mEfCAT71bsCxpoQ" name="Consejo directivo">
        <elements xmi:type="process:StartTimerEvent" xmi:id="_ZqQRsI9mEfCAT71bsCxpoQ" name="15 dias" outgoing="_ZqRf0I9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZqQRsY9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZqQRso9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZqQRs49mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_ZqQRtI9mEfCAT71bsCxpoQ" name="0 0 12 1/15 * ? *" content="0 0 12 1/15 * ? *"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZqQ4z49mEfCAT71bsCxpoQ" documentation="Ver si esto lo pones como tarea automatica que haga un GET a un endpoint del cloud que traiga todos los proyectos en ejecucion. &#xD;&#xA;Habria que hacer el conector y una variable que tome la respuesta de la peticion.&#xD;&#xA;Si no la otra haces el get por afuera " name="Revisar ejecución de los proyectos" outgoing="_nUejIMYmEfCAQPVkCXfpoQ" incoming="_ZqRf0I9mEfCAT71bsCxpoQ" actor="_ZqQ4zo9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZqQ40I9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZqQ40Y9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZqQ40o9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZqQ4049mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZqQ41I9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZqQ41Y9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZqQ41o9mEfCAT71bsCxpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZqQ4149mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZqQ42I9mEfCAT71bsCxpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_AuPtMMV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZqQ42o9mEfCAT71bsCxpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZqQ4249mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ZqQ4349mEfCAT71bsCxpoQ" name="Cargar observaciones y mejoras" outgoing="_kxuVYI9mEfCAT71bsCxpoQ" incoming="_Dsq9MMYmEfCAQPVkCXfpoQ" actor="_ZqQ4zo9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZqQ44I9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZqQ44Y9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZqQ44o9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZqQ4449mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZqQ45I9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZqQ45Y9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZqQ45o9mEfCAT71bsCxpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZqQ4549mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ZqQ46I9mEfCAT71bsCxpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_AuPtMcV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ZqQ46o9mEfCAT71bsCxpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ZqQ4649mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_AHT_sMD6EfC997thP10FkQ" name="Tiene observaciones?" outgoing="_GERGUMD6EfC997thP10FkQ _UngGQMD6EfC997thP10FkQ" incoming="_kxuVYI9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_AHT_scD6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_AHT_ssD6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_AHT_s8D6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_NZgOgMD6EfC997thP10FkQ" name="Fin" incoming="_UngGQMD6EfC997thP10FkQ _gVtaMMYmEfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NZhcocD6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NZhcoMD6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NZhcosD6EfC997thP10FkQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8QjJ4MYlEfCAQPVkCXfpoQ" name="Hay proyectos?" outgoing="_Dsq9MMYmEfCAQPVkCXfpoQ _gVtaMMYmEfCAQPVkCXfpoQ" incoming="_nUejIMYmEfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8Qm0QcYlEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8Qm0QMYlEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8Qm0QsYlEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NQiDoMYnEfCAQPVkCXfpoQ" documentation="TODO: hacer conector de entrada que suba al endpoint del cloud ponerObservacion. No se si habria que hacer otra variable para el project id o vendria todo en el payload" name="subir observacion" outgoing="_fVO_MMYnEfCAQPVkCXfpoQ" incoming="_GERGUMD6EfC997thP10FkQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NQiqscYnEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NQiqsMYnEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NQiqssYnEfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NQiqs8YnEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NQiqtMYnEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NQiqtcYnEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NQiqt8YnEfCAQPVkCXfpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NQiqtsYnEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_bHXI4I9mEfCAT71bsCxpoQ" name="Ong originante">
        <elements xmi:type="process:Task" xmi:id="_iPtEkY9mEfCAT71bsCxpoQ" name="Aplicar correcciones (máx. 5 días)" outgoing="_n9bcYI9mEfCAT71bsCxpoQ" incoming="_fVO_MMYnEfCAQPVkCXfpoQ" actor="_iPtEkI9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iPtEko9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iPtEk49mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iPtElI9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iPtElY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iPtElo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iPtEl49mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iPtEmI9mEfCAT71bsCxpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iPtEmY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iPtEmo9mEfCAT71bsCxpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_AuPtMsV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iPtEnI9mEfCAT71bsCxpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iPtEnY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_ZqQ4749mEfCAT71bsCxpoQ" name="Fin de observaciones" incoming="_n9bcYI9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZqQ48I9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZqQ48Y9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZqQ48o9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_Dd32YMD7EfC997thP10FkQ" name="tieneObservaciones" dataType="_5NttwI58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Dd32YcD7EfC997thP10FkQ" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_cQregMYmEfCAQPVkCXfpoQ" documentation="Variable que dice si hay al menos 1 proyecto en ejecucion" name="hayProyectos" dataType="_5NttwI58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_cQregcYmEfCAQPVkCXfpoQ" name="hayProyectos" content="hayProyectos" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_HAC9AMYnEfCAQPVkCXfpoQ" documentation="Contenido json de la observacion que carga el front para que bonita lo envie al cloud" name="observacion" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_HAC9AcYnEfCAQPVkCXfpoQ" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_5Qf8EI58EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_AuPtM8V2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_5Qf8Eo58EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_5Qf8E458EfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZqRf0I9mEfCAT71bsCxpoQ" target="_ZqQ4z49mEfCAT71bsCxpoQ" source="_ZqQRsI9mEfCAT71bsCxpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZqRf0Y9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZqRf0o9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kxuVYI9mEfCAT71bsCxpoQ" target="_AHT_sMD6EfC997thP10FkQ" source="_ZqQ4349mEfCAT71bsCxpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kxuVYY9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kxuVYo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n9bcYI9mEfCAT71bsCxpoQ" target="_ZqQ4749mEfCAT71bsCxpoQ" source="_iPtEkY9mEfCAT71bsCxpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n9bcYY9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_n9bcYo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GERGUMD6EfC997thP10FkQ" name="Si" target="_NQiDoMYnEfCAQPVkCXfpoQ" source="_AHT_sMD6EfC997thP10FkQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GEUwsMD6EfC997thP10FkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GEUwscD6EfC997thP10FkQ" name="tieneObservaciones" content="tieneObservaciones" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_IfYocMD7EfC997thP10FkQ" name="tieneObservaciones" dataType="_5NttwI58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UngGQMD6EfC997thP10FkQ" name="No" target="_NZgOgMD6EfC997thP10FkQ" source="_AHT_sMD6EfC997thP10FkQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UngGQcD6EfC997thP10FkQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UngGQsD6EfC997thP10FkQ" name="!tieneObservaciones" content="!tieneObservaciones" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Dsq9MMYmEfCAQPVkCXfpoQ" name="Si" target="_ZqQ4349mEfCAT71bsCxpoQ" source="_8QjJ4MYlEfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DsrkQMYmEfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DsrkQcYmEfCAQPVkCXfpoQ" name="hayProyectos" content="hayProyectos" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_cQ6IAMYmEfCAQPVkCXfpoQ" documentation="Variable que dice si hay al menos 1 proyecto en ejecucion" name="hayProyectos" dataType="_5NttwI58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gVtaMMYmEfCAQPVkCXfpoQ" name="No" target="_NZgOgMD6EfC997thP10FkQ" source="_8QjJ4MYlEfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gVtaMcYmEfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_gVtaMsYmEfCAQPVkCXfpoQ" name="hayProyectos" content="hayProyectos" type="TYPE_VARIABLE" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_i5m6UMYmEfCAQPVkCXfpoQ" documentation="Variable que dice si hay al menos 1 proyecto en ejecucion" name="hayProyectos" dataType="_5NttwI58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nUejIMYmEfCAQPVkCXfpoQ" target="_8QjJ4MYlEfCAQPVkCXfpoQ" source="_ZqQ4z49mEfCAT71bsCxpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nUfKMMYmEfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_nUfKMcYmEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fVO_MMYnEfCAQPVkCXfpoQ" target="_iPtEkY9mEfCAT71bsCxpoQ" source="_NQiDoMYnEfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fVO_McYnEfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_fVO_MsYnEfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_2uHpYI59EfCez5hyndgAQQ" name="Red de ongs"/>
      <actors xmi:type="process:Actor" xmi:id="_ZqQ4zo9mEfCAT71bsCxpoQ" name="Consejo directivo"/>
      <actors xmi:type="process:Actor" xmi:id="_iPtEkI9mEfCAT71bsCxpoQ" name="Ong originante"/>
      <contract xmi:type="process:Contract" xmi:id="_5Qf8FI58EfCez5hyndgAQQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Qf8AY58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Qf8Ao58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Qf8A458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Qf8BI58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Qf8BY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Qf8Bo58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Qf8B458EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Qf8CI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Qf8CY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Qf8Co58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Qf8C458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Qf8DI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Qf8DY58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Qf8Do58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Qf8D458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_5ODE8I58EfCez5hyndgAQQ" documentation="&#xD;&#xA;" name="ONG Originante y red de ongs">
      <elements xmi:type="process:Lane" xmi:id="_kAMAMI9lEfCAT71bsCxpoQ" name="Ong originante">
        <elements xmi:type="process:StartEvent" xmi:id="_5OLn0I58EfCez5hyndgAQQ" name="Inicio" outgoing="_5RzjkI58EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5OMO4Y58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5OMO4I58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5OMO4o58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_5OvogI58EfCez5hyndgAQQ" name="¿Todas las etapas cubiertas?" outgoing="_5SWWII58EfCez5hyndgAQQ _T7h0UI9mEfCAT71bsCxpoQ" incoming="_DoATEMY7EfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5Ovogo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5OvogY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5Ovog458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_5Pjg0I58EfCez5hyndgAQQ" name="Proyecto finalizado" incoming="_kkf0MMY5EfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5Pjg0o58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5Pjg0Y58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5Pjg0458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_yPBn4I59EfCez5hyndgAQQ" documentation="La ong originante marca que empezo la ejecucion, esto deberia tener un conector de salida u otra tarea que avise al cloud" name="Ejecutar proyecto" outgoing="_jWyBYI9mEfCAT71bsCxpoQ" incoming="_1Eq04I9lEfCAT71bsCxpoQ" actor="_5Mvn8I59EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5PJ4MY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5PJ4MI58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5PJ4Mo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5PJ4NY58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5PJ4No58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5PJ4N458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5PJ4OY58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5PJ4OI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_yPCO9I59EfCez5hyndgAQQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Az_v4MV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_yPCO8459EfCez5hyndgAQQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_yPCO9o59EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D6XoQI5-EfCez5hyndgAQQ" documentation="La ong originante crea el " name="Crear proyecto" outgoing="_8mAC4I9mEfCAT71bsCxpoQ" incoming="_5RzjkI58EfCez5hyndgAQQ" actor="_5Mvn8I59EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5ORHYo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5ORHYY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5ORHY458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5ORHZI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5ORHZY58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5ORHZo58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5ORHaI58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5ORHZ458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D6YPWY5-EfCez5hyndgAQQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Az_v4cV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D6YPWI5-EfCez5hyndgAQQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D6YPW45-EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Jg5L4I5-EfCez5hyndgAQQ" documentation="Aca la ong decide si aceptar o rechazar la colaboracion" name="Carga respuesta" outgoing="_5SRdoI58EfCez5hyndgAQQ" incoming="_okGIMMY3EfCAQPVkCXfpoQ" actor="_5Mvn8I59EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5OrXEo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5OrXEY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5OrXE458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5OrXFI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5OrXFY58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5OrXFo58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5OrXGI58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5OrXF458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Jg5y-Y5-EfCez5hyndgAQQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Az_v4sV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Jg5y-I5-EfCez5hyndgAQQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Jg5y-45-EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_JkqUgMTXEfCLWsvb-f-qjg" name="Registrar pedidos de cobertura" outgoing="_FA3y4I9mEfCAT71bsCxpoQ" incoming="_8mAC4I9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5OhmEo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5OhmEY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5OhmE458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_zXbKQMP6EfCDFpWNGSzyfg" documentation="Se hace el POST al endpoint del cloud" name="Registrar pedidos de ayuda" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.4.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_zXbKQcP6EfCDFpWNGSzyfg" definitionId="rest-post" version="1.4.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKQsP6EfCDFpWNGSzyfg" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKQ8P6EfCDFpWNGSzyfg" name="url()" content="registarPedidoAyudaEndpoint" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_wEBrgMTZEfCLWsvb-f-qjg" documentation="Endpoint de registrarPedidoAyuda" name="registarPedidoAyudaEndpoint" dataType="_5NttxY58EfCez5hyndgAQQ"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKRMP6EfCDFpWNGSzyfg" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKRcP6EfCDFpWNGSzyfg" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKRsP6EfCDFpWNGSzyfg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKR8P6EfCDFpWNGSzyfg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKSMP6EfCDFpWNGSzyfg" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_zXbKScP6EfCDFpWNGSzyfg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKSsP6EfCDFpWNGSzyfg" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_zXbKS8P6EfCDFpWNGSzyfg">
                  <expressions xmi:type="expression:ListExpression" xmi:id="_Sj_7AMP7EfCDFpWNGSzyfg">
                    <expressions xmi:type="expression:Expression" xmi:id="_Sj_7AcP7EfCDFpWNGSzyfg" name="Authorization" content="Authorization"/>
                    <expressions xmi:type="expression:Expression" xmi:id="_Sj_7AsP7EfCDFpWNGSzyfg" name="tokenJWT" content="'Bearer ' + tokenJWT" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                      <referencedElements xmi:type="process:Data" xmi:id="_4EGnoMSxEfCzOIE9nJrBKA" name="tokenJWT" dataType="_5NttxY58EfCez5hyndgAQQ"/>
                    </expressions>
                  </expressions>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKTMP6EfCDFpWNGSzyfg" key="add_bonita_context_headers">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKTcP6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKTsP6EfCDFpWNGSzyfg" key="bonita_activity_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKT8P6EfCDFpWNGSzyfg" name="X-Bonita-Activity-Instance-Id" content="X-Bonita-Activity-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKUMP6EfCDFpWNGSzyfg" key="bonita_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKUcP6EfCDFpWNGSzyfg" name="X-Bonita-Process-Instance-Id" content="X-Bonita-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKUsP6EfCDFpWNGSzyfg" key="bonita_root_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKU8P6EfCDFpWNGSzyfg" name="X-Bonita-Root-Process-Instance-Id" content="X-Bonita-Root-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKVMP6EfCDFpWNGSzyfg" key="bonita_process_definition_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKVcP6EfCDFpWNGSzyfg" name="X-Bonita-Process-Definition-Id" content="X-Bonita-Process-Definition-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKVsP6EfCDFpWNGSzyfg" key="bonita_task_assignee_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKV8P6EfCDFpWNGSzyfg" name="X-Bonita-Task-Assignee-Id" content="X-Bonita-Task-Assignee-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKWMP6EfCDFpWNGSzyfg" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKWcP6EfCDFpWNGSzyfg" name="proyecto" content="proyecto" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_78UzIMVxEfCfIZFzr1aU_g" documentation="Proyecto que la ong originante carga al cloud" name="proyecto" dataType="_5NttxY58EfCez5hyndgAQQ"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKWsP6EfCDFpWNGSzyfg" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKW8P6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKXMP6EfCDFpWNGSzyfg" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKXcP6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKXsP6EfCDFpWNGSzyfg" key="fail_on_http_4xx">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKX8P6EfCDFpWNGSzyfg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKYMP6EfCDFpWNGSzyfg" key="fail_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKYcP6EfCDFpWNGSzyfg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKYsP6EfCDFpWNGSzyfg" key="failure_exception_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_zXbKY8P6EfCDFpWNGSzyfg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKZMP6EfCDFpWNGSzyfg" key="retry_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKZcP6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKZsP6EfCDFpWNGSzyfg" key="retry_additional_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_zXbKZ8P6EfCDFpWNGSzyfg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKaMP6EfCDFpWNGSzyfg" key="max_body_content_printed">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKacP6EfCDFpWNGSzyfg" name="1000" content="1000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKasP6EfCDFpWNGSzyfg" key="sensitive_headers_printed">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKa8P6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKbMP6EfCDFpWNGSzyfg" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKbcP6EfCDFpWNGSzyfg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKbsP6EfCDFpWNGSzyfg" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKb8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKcMP6EfCDFpWNGSzyfg" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKccP6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKcsP6EfCDFpWNGSzyfg" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKc8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKdMP6EfCDFpWNGSzyfg" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKdcP6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKdsP6EfCDFpWNGSzyfg" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKd8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKeMP6EfCDFpWNGSzyfg" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKecP6EfCDFpWNGSzyfg" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKesP6EfCDFpWNGSzyfg" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKe8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKfMP6EfCDFpWNGSzyfg" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKfcP6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKfsP6EfCDFpWNGSzyfg" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKf8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKgMP6EfCDFpWNGSzyfg" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKgcP6EfCDFpWNGSzyfg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKgsP6EfCDFpWNGSzyfg" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKg8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKhMP6EfCDFpWNGSzyfg" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKhcP6EfCDFpWNGSzyfg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKhsP6EfCDFpWNGSzyfg" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKh8P6EfCDFpWNGSzyfg" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKiMP6EfCDFpWNGSzyfg" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKicP6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKisP6EfCDFpWNGSzyfg" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKi8P6EfCDFpWNGSzyfg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKjMP6EfCDFpWNGSzyfg" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKjcP6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKjsP6EfCDFpWNGSzyfg" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKj8P6EfCDFpWNGSzyfg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKkMP6EfCDFpWNGSzyfg" key="automatic_proxy_resolution">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKkcP6EfCDFpWNGSzyfg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKksP6EfCDFpWNGSzyfg" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKk8P6EfCDFpWNGSzyfg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKlMP6EfCDFpWNGSzyfg" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKlcP6EfCDFpWNGSzyfg" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_zXbKlsP6EfCDFpWNGSzyfg" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_zXbKl8P6EfCDFpWNGSzyfg" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_zXbKmMP6EfCDFpWNGSzyfg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zXbKmcP6EfCDFpWNGSzyfg" name="restBody" content="restBody" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_UFSk8MV3EfCfIZFzr1aU_g" documentation="variable de debug para ver el resultado de la peticion http mas reciente" name="restBody" dataType="_5NttxY58EfCez5hyndgAQQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zXbKmsP6EfCDFpWNGSzyfg" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_zXbKm8P6EfCDFpWNGSzyfg" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zXbKnMP6EfCDFpWNGSzyfg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_zXbKncP6EfCDFpWNGSzyfg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zXbKnsP6EfCDFpWNGSzyfg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zXbKn8P6EfCDFpWNGSzyfg" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_zXbKoMP6EfCDFpWNGSzyfg" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zXbKocP6EfCDFpWNGSzyfg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_zXbKosP6EfCDFpWNGSzyfg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zXbKo8P6EfCDFpWNGSzyfg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zXbKpMP6EfCDFpWNGSzyfg" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_zXbKpcP6EfCDFpWNGSzyfg" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zXbKpsP6EfCDFpWNGSzyfg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_zXbKp8P6EfCDFpWNGSzyfg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zXbKqMP6EfCDFpWNGSzyfg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zXbKqcP6EfCDFpWNGSzyfg" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_zXbKqsP6EfCDFpWNGSzyfg" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zXbKq8P6EfCDFpWNGSzyfg" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_zXbKrMP6EfCDFpWNGSzyfg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zXbKrcP6EfCDFpWNGSzyfg"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zXbKrsP6EfCDFpWNGSzyfg" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_zXbKr8P6EfCDFpWNGSzyfg" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zXbKsMP6EfCDFpWNGSzyfg" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5OhmFI58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5OhmFY58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5OhmFo58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5OhmGI58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5OhmF458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_6VY_kMY3EfCAQPVkCXfpoQ" name="Marcar proyecto como completo" outgoing="_1Eq04I9lEfCAT71bsCxpoQ" incoming="_5SWWII58EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5O9q8o58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5O9q8Y58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5O9q8458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5O9q9I58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5O9q9Y58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5O9q9o58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5O-SAI58EfCez5hyndgAQQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5O9q9458EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ScneQMY4EfCAQPVkCXfpoQ" documentation="Ong originante marca un compromiso de los disponibles como terminado. Desde el front se deberia incrementar la variable pedidosTotales antes de completar esta tarea" name="Compromiso terminado" outgoing="_kCJxkMY4EfCAQPVkCXfpoQ" incoming="_jWyBYI9mEfCAT71bsCxpoQ _nyMUsMY4EfCAQPVkCXfpoQ" actor="_5Mvn8I59EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ScneQsY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ScneQcY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ScneQ8Y4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ScneRMY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ScneRcY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ScneRsY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ScneSMY4EfCAQPVkCXfpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ScneR8Y4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ScneSsY4EfCAQPVkCXfpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ScneS8Y4EfCAQPVkCXfpoQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ScneScY4EfCAQPVkCXfpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ScneTMY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_b_b4UMY4EfCAQPVkCXfpoQ" name="Quedan compromisos?" outgoing="_nyMUsMY4EfCAQPVkCXfpoQ _BXJVoMY5EfCAQPVkCXfpoQ" incoming="_kCJxkMY4EfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b_cfYcY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b_cfYMY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b_cfYsY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_3PAA8MY4EfCAQPVkCXfpoQ" documentation="La ong originante marca el proyecto como terminado. No se activa automaticamente al terminar todos los compromisos porque pueden quedar etapas sin compromisos que no hayan terminado" name="Marcar proyecto como finalizado" outgoing="_kkf0MMY5EfCAQPVkCXfpoQ" incoming="_BXJVoMY5EfCAQPVkCXfpoQ" actor="_5Mvn8I59EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3PAoAcY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3PAoAMY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3PAoAsY4EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3PAoA8Y4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3PAoBMY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3PAoBcY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3PAoB8Y4EfCAQPVkCXfpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3PAoBsY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_3PAoCcY4EfCAQPVkCXfpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_3PAoCsY4EfCAQPVkCXfpoQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_3PAoCMY4EfCAQPVkCXfpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_3PAoC8Y4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_hyl30MY6EfCAQPVkCXfpoQ" name="Acepta compromiso?" outgoing="_lSyoIMY6EfCAQPVkCXfpoQ _yZVnoMY6EfCAQPVkCXfpoQ" incoming="_5SRdoI58EfCez5hyndgAQQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hyme4cY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hyme4MY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hyme4sY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wYfKMMY6EfCAQPVkCXfpoQ" documentation="Tendria que pegarle al cloud y aumentar en 1 la variable de pedidosActuales" name="Subir aceptacion" outgoing="_DoATEMY7EfCAQPVkCXfpoQ" incoming="_yZVnoMY6EfCAQPVkCXfpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wYfxQcY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wYfxQMY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wYfxQsY6EfCAQPVkCXfpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wYfxQ8Y6EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wYfxRMY6EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wYfxRcY6EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wYfxR8Y6EfCAQPVkCXfpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wYfxRsY6EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_nYD68I9lEfCAT71bsCxpoQ" name="Red de ongs">
        <elements xmi:type="process:Task" xmi:id="_G9M8yY9mEfCAT71bsCxpoQ" name="Cargar compromiso" outgoing="_G9OK0I9mEfCAT71bsCxpoQ" incoming="_FA3y4I9mEfCAT71bsCxpoQ _T7h0UI9mEfCAT71bsCxpoQ _lSyoIMY6EfCAQPVkCXfpoQ" actor="_G9M8uI9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G9M8yo9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G9M8y49mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G9M8zI9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G9M8zY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G9M8zo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G9M8z49mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G9M80I9mEfCAT71bsCxpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G9M80Y9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_G9M80o9mEfCAT71bsCxpoQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_Az_v5cV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_G9M81I9mEfCAT71bsCxpoQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_G9M81Y9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_mF_HAMY3EfCAQPVkCXfpoQ" name="Subir compromiso" outgoing="_okGIMMY3EfCAQPVkCXfpoQ" incoming="_G9OK0I9mEfCAT71bsCxpoQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G9M8uo9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G9M8u49mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G9M8vI9mEfCAT71bsCxpoQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G9M8vY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G9M8vo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G9M8v49mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G9M8wI9mEfCAT71bsCxpoQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G9M8wY9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_YGdWQJozEfCoG5yL5Ss25g" documentation="Nombre identificador y único de la ONG" name="id" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_YGd9UJozEfCoG5yL5Ss25g" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_X6mPEJo0EfCoG5yL5Ss25g" documentation="Cantidad de pedidos en el proyecto. Puede tomar el valor 0." name="pedidosTotales" dataType="_5Nttwo58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_X6mPEZo0EfCoG5yL5Ss25g" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_sBB1AJo4EfCoG5yL5Ss25g" documentation="Cantidad de pedidos actuales, es comparado con los totales para ver si ya se alcanzaron. Empieza en 0." name="pedidosActuales" dataType="_5Nttwo58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_sBB1AZo4EfCoG5yL5Ss25g" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_wAtq4MSvEfCzOIE9nJrBKA" name="tokenJWT" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_wAtq4cSvEfCzOIE9nJrBKA" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_Ksf0YMTZEfCLWsvb-f-qjg" documentation="Endpoint de registrarPedidoAyuda" name="registarPedidoAyudaEndpoint" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Ksf0YcTZEfCLWsvb-f-qjg" name="http://localhost:8000/api/v1/projects/registrarPedidoAyuda" content="http://localhost:8000/api/v1/projects/registrarPedidoAyuda"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_yyWW4MVxEfCfIZFzr1aU_g" documentation="Proyecto que la ong originante carga al cloud" name="proyecto" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_yyWW4cVxEfCfIZFzr1aU_g" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_O1wlAMV3EfCfIZFzr1aU_g" documentation="variable de debug para ver el resultado de la peticion http mas reciente" name="restBody" dataType="_5NttxY58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_O1wlAcV3EfCfIZFzr1aU_g" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_y0_TwMY4EfCAQPVkCXfpoQ" documentation="Contador que dice cuantos pedidos del proyecto se terminaron" name="pedidosTerminados" dataType="_5Nttwo58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_y0_TwcY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_qy3lgMY6EfCAQPVkCXfpoQ" documentation="Indica si la ong originante acepta un compromiso de colaboracion de una ong de la red" name="aceptaCompromiso" dataType="_5NttwI58EfCez5hyndgAQQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_qy3lgcY6EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_5ODsCI58EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_Az_v5sV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_5ODsCo58EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_5ODsC458EfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5RzjkI58EfCez5hyndgAQQ" target="_D6XoQI5-EfCez5hyndgAQQ" source="_5OLn0I58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5RzjkY58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5Rzjko58EfCez5hyndgAQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5SRdoI58EfCez5hyndgAQQ" target="_hyl30MY6EfCAQPVkCXfpoQ" source="_Jg5L4I5-EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5SRdoY58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5SRdoo58EfCez5hyndgAQQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5SWWII58EfCez5hyndgAQQ" name="Si" target="_6VY_kMY3EfCAQPVkCXfpoQ" source="_5OvogI58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5SWWIY58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5SbOoI58EfCez5hyndgAQQ" name="pedidosCubiertos()" content="return pedidosActuales == pedidosTotales;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_Tha5QJo9EfCoG5yL5Ss25g" documentation="Cantidad de pedidos actuales, es comparado con los totales para ver si ya se alcanzaron. Empieza en 0." name="pedidosActuales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
          <referencedElements xmi:type="process:Data" xmi:id="_Tha5QZo9EfCoG5yL5Ss25g" documentation="Cantidad de pedidos en el proyecto. Puede tomar el valor 0." name="pedidosTotales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1Eq04I9lEfCAT71bsCxpoQ" target="_yPBn4I59EfCez5hyndgAQQ" source="_6VY_kMY3EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1Erb8I9lEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1Erb8Y9lEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FA3y4I9mEfCAT71bsCxpoQ" target="_G9M8yY9mEfCAT71bsCxpoQ" source="_JkqUgMTXEfCLWsvb-f-qjg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FA3y4Y9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_FA4Z8I9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_G9OK0I9mEfCAT71bsCxpoQ" target="_mF_HAMY3EfCAQPVkCXfpoQ" source="_G9M8yY9mEfCAT71bsCxpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_G9OK0Y9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_G9OK0o9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_T7h0UI9mEfCAT71bsCxpoQ" name="No" target="_G9M8yY9mEfCAT71bsCxpoQ" source="_5OvogI58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_T7ibYI9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_T7ibYY9mEfCAT71bsCxpoQ" name="!pedidosCubiertos()" content="return pedidosActuales &lt; pedidosTotales; " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_ZeqTwJo9EfCoG5yL5Ss25g" documentation="Cantidad de pedidos actuales, es comparado con los totales para ver si ya se alcanzaron. Empieza en 0." name="pedidosActuales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
          <referencedElements xmi:type="process:Data" xmi:id="_ZeqTwZo9EfCoG5yL5Ss25g" documentation="Cantidad de pedidos en el proyecto. Puede tomar el valor 0." name="pedidosTotales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jWyBYI9mEfCAT71bsCxpoQ" target="_ScneQMY4EfCAQPVkCXfpoQ" source="_yPBn4I59EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jWyBYY9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jWyBYo9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8mAC4I9mEfCAT71bsCxpoQ" target="_JkqUgMTXEfCLWsvb-f-qjg" source="_D6XoQI5-EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8mAC4Y9mEfCAT71bsCxpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_8mAC4o9mEfCAT71bsCxpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_okGIMMY3EfCAQPVkCXfpoQ" target="_Jg5L4I5-EfCez5hyndgAQQ" source="_mF_HAMY3EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_okGIMcY3EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_okGIMsY3EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kCJxkMY4EfCAQPVkCXfpoQ" target="_b_b4UMY4EfCAQPVkCXfpoQ" source="_ScneQMY4EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kCKYoMY4EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kCKYocY4EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nyMUsMY4EfCAQPVkCXfpoQ" name="Si" target="_ScneQMY4EfCAQPVkCXfpoQ" source="_b_b4UMY4EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nyMUscY4EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_nyMUssY4EfCAQPVkCXfpoQ" name="newScript()" content="return pedidosTerminados &lt; pedidosTotales; " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_WomhEMY5EfCAQPVkCXfpoQ" documentation="Contador que dice cuantos pedidos del proyecto se terminaron" name="pedidosTerminados" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
          <referencedElements xmi:type="process:Data" xmi:id="_WomhEcY5EfCAQPVkCXfpoQ" documentation="Cantidad de pedidos en el proyecto. Puede tomar el valor 0." name="pedidosTotales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BXJVoMY5EfCAQPVkCXfpoQ" name="No" target="_3PAA8MY4EfCAQPVkCXfpoQ" source="_b_b4UMY4EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BXJVocY5EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_BXJVosY5EfCAQPVkCXfpoQ" name="newScript()" content="return pedidosTerminados == pedidosTotales " interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_KblKkMY5EfCAQPVkCXfpoQ" documentation="Contador que dice cuantos pedidos del proyecto se terminaron" name="pedidosTerminados" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
          <referencedElements xmi:type="process:Data" xmi:id="_KblKkcY5EfCAQPVkCXfpoQ" documentation="Cantidad de pedidos en el proyecto. Puede tomar el valor 0." name="pedidosTotales" dataType="_5Nttwo58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_kkf0MMY5EfCAQPVkCXfpoQ" target="_5Pjg0I58EfCez5hyndgAQQ" source="_3PAA8MY4EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_kkf0McY5EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_kkf0MsY5EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lSyoIMY6EfCAQPVkCXfpoQ" name="No" target="_G9M8yY9mEfCAT71bsCxpoQ" source="_hyl30MY6EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lSyoIcY6EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_lSyoIsY6EfCAQPVkCXfpoQ" name="newScript()" content="return aceptaCompromiso" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_17dqkMY6EfCAQPVkCXfpoQ" documentation="Indica si la ong originante acepta un compromiso de colaboracion de una ong de la red" name="aceptaCompromiso" dataType="_5NttwI58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yZVnoMY6EfCAQPVkCXfpoQ" name="Si" target="_wYfKMMY6EfCAQPVkCXfpoQ" source="_hyl30MY6EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yZVnocY6EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_yZVnosY6EfCAQPVkCXfpoQ" name="newScript()" content="return aceptaCompromiso" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_02auEMY6EfCAQPVkCXfpoQ" documentation="Indica si la ong originante acepta un compromiso de colaboracion de una ong de la red" name="aceptaCompromiso" dataType="_5NttwI58EfCez5hyndgAQQ"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DoATEMY7EfCAQPVkCXfpoQ" target="_5OvogI58EfCez5hyndgAQQ" source="_wYfKMMY6EfCAQPVkCXfpoQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DoATEcY7EfCAQPVkCXfpoQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DoATEsY7EfCAQPVkCXfpoQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_5Mvn8I59EfCez5hyndgAQQ" name="Ong originante" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_G9M8uI9mEfCAT71bsCxpoQ" name="Red de ongs"/>
      <contract xmi:type="process:Contract" xmi:id="_5ODsDI58EfCez5hyndgAQQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5ODE8Y58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5ODE8o58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5ODE8458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5ODE9I58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5ODE9Y58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5ODE9o58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5ODE9458EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5ODsAI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5ODsAY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5ODsAo58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5ODsA458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5ODsBI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5ODsBY58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5ODsBo58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5ODsB458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_5RezcI58EfCez5hyndgAQQ" name="Ejecución del proyecto">
      <elements xmi:type="process:StartEvent" xmi:id="_5RmvQI58EfCez5hyndgAQQ" name="Inicio ejecución" outgoing="_5RurEI58EfCez5hyndgAQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_5RmvQo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_5RmvQY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_5RmvQ458EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_5RrAsI58EfCez5hyndgAQQ" name="Fin ejecución" incoming="_5RurEI58EfCez5hyndgAQQ">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_5RrnwY58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_5RrnwI58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_5Rrnwo58EfCez5hyndgAQQ" name="" content="" returnTypeFixed="true"/>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_5Rfaj458EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_Avts0MV2EfCfIZFzr1aU_g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_5RfakY58EfCez5hyndgAQQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_5Rfako58EfCez5hyndgAQQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5RurEI58EfCez5hyndgAQQ" target="_5RrAsI58EfCez5hyndgAQQ" source="_5RmvQI58EfCez5hyndgAQQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5RurEY58EfCez5hyndgAQQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5RurEo58EfCez5hyndgAQQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_5Rfak458EfCez5hyndgAQQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5RfagI58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5RfagY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Rfago58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Rfag458EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5RfahI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5RfahY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5Rfaho58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Rfah458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5RfaiI58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5RfaiY58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5Rfaio58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Rfai458EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_5RfajI58EfCez5hyndgAQQ">
        <name xmi:type="expression:Expression" xmi:id="_5RfajY58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_5Rfajo58EfCez5hyndgAQQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_5NttwI58EfCez5hyndgAQQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_5NttwY58EfCez5hyndgAQQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_5Nttwo58EfCez5hyndgAQQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_5Nttw458EfCez5hyndgAQQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_5NttxI58EfCez5hyndgAQQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_5NttxY58EfCez5hyndgAQQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_5Nttxo58EfCez5hyndgAQQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_5Nttx458EfCez5hyndgAQQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_5NttyI58EfCez5hyndgAQQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_5NtGsY58EfCez5hyndgAQQ" type="Process" element="_5NtGsI58EfCez5hyndgAQQ" name="Defs_ProjectPlanning" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_5QgjEI58EfCez5hyndgAQQ" type="2007" element="_5Qf8AI58EfCez5hyndgAQQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_5QhKJI58EfCez5hyndgAQQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_5QhKJY58EfCez5hyndgAQQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_a4HzAI9mEfCAT71bsCxpoQ" type="3007" element="_a4HL8I9mEfCAT71bsCxpoQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_a4HzBY9mEfCAT71bsCxpoQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_a4HzBo9mEfCAT71bsCxpoQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ZqQRtY9mEfCAT71bsCxpoQ" type="3016" element="_ZqQRsI9mEfCAT71bsCxpoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZqQRto9mEfCAT71bsCxpoQ" type="5031" element="_ZqQRsI9mEfCAT71bsCxpoQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZqQRt49mEfCAT71bsCxpoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZqQRuI9mEfCAT71bsCxpoQ" x="44" y="138"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZqQ43I9mEfCAT71bsCxpoQ" type="3005" element="_ZqQ4z49mEfCAT71bsCxpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZqQ43Y9mEfCAT71bsCxpoQ" type="5005" element="_ZqQ4z49mEfCAT71bsCxpoQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZqQ43o9mEfCAT71bsCxpoQ" x="138" y="115" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZqQ47I9mEfCAT71bsCxpoQ" type="3005" element="_ZqQ4349mEfCAT71bsCxpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZqQ47Y9mEfCAT71bsCxpoQ" type="5005" element="_ZqQ4349mEfCAT71bsCxpoQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZqQ47o9mEfCAT71bsCxpoQ" x="452" y="91" width="145" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AHT_tMD6EfC997thP10FkQ" type="3008" element="_AHT_sMD6EfC997thP10FkQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_AHT_tcD6EfC997thP10FkQ" type="5026" element="_AHT_sMD6EfC997thP10FkQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_AHT_tsD6EfC997thP10FkQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AHT_t8D6EfC997thP10FkQ" x="680" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NZiDsMD6EfC997thP10FkQ" type="3003" element="_NZgOgMD6EfC997thP10FkQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NZiDssD6EfC997thP10FkQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NZiDs8D6EfC997thP10FkQ" x="28" y="-20"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NZiDscD6EfC997thP10FkQ" x="687" y="18"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8QqeoMYlEfCAQPVkCXfpoQ" type="3008" element="_8QjJ4MYlEfCAQPVkCXfpoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8QqeosYlEfCAQPVkCXfpoQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8Qqeo8YlEfCAQPVkCXfpoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8QqeocYlEfCAQPVkCXfpoQ" x="343" y="134"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NQj40MYnEfCAQPVkCXfpoQ" type="3027" element="_NQiDoMYnEfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NQj40sYnEfCAQPVkCXfpoQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NQj40cYnEfCAQPVkCXfpoQ" x="419" y="266"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_a4HzAY9mEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_a4HzAo9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_a4HzA49mEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_a4HzB49mEfCAT71bsCxpoQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_a4HzBI9mEfCAT71bsCxpoQ" x="53" y="10" width="787" height="331"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_bHYXAI9mEfCAT71bsCxpoQ" type="3007" element="_bHXI4I9mEfCAT71bsCxpoQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_bHYXBY9mEfCAT71bsCxpoQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_bHYXBo9mEfCAT71bsCxpoQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_iPtEno9mEfCAT71bsCxpoQ" type="3005" element="_iPtEkY9mEfCAT71bsCxpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iPtEn49mEfCAT71bsCxpoQ" type="5005" element="_iPtEkY9mEfCAT71bsCxpoQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iPtEoI9mEfCAT71bsCxpoQ" x="308" y="40" width="192" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZqQ4849mEfCAT71bsCxpoQ" type="3003" element="_ZqQ4749mEfCAT71bsCxpoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZqQ49I9mEfCAT71bsCxpoQ" type="5025" element="_ZqQ4749mEfCAT71bsCxpoQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZqQ49Y9mEfCAT71bsCxpoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZqQ49o9mEfCAT71bsCxpoQ" x="625" y="55"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_bHYXAY9mEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_bHYXAo9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_bHYXA49mEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_bHYXB49mEfCAT71bsCxpoQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bHYXBI9mEfCAT71bsCxpoQ" x="53" y="303" width="787" height="196"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_5QhKII58EfCez5hyndgAQQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5QhKIY58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_5QhKIo58EfCez5hyndgAQQ" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_5QhKJo58EfCez5hyndgAQQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5QhKI458EfCez5hyndgAQQ" width="815" height="303"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_5RgBkI58EfCez5hyndgAQQ" type="2007" element="_5RezcI58EfCez5hyndgAQQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_5RgBlY58EfCez5hyndgAQQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_5RgBlo58EfCez5hyndgAQQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_5RnWUI58EfCez5hyndgAQQ" type="3002" element="_5RmvQI58EfCez5hyndgAQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_5Rn9YI58EfCez5hyndgAQQ" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_5Rn9YY58EfCez5hyndgAQQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5RnWUY58EfCez5hyndgAQQ" x="-20" y="-20"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_5Rrnw458EfCez5hyndgAQQ" type="3003" element="_5RrAsI58EfCez5hyndgAQQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_5RrnxY58EfCez5hyndgAQQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_5Rrnxo58EfCez5hyndgAQQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5RrnxI58EfCez5hyndgAQQ" x="-20" y="-20"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_5RgBkY58EfCez5hyndgAQQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5RgBko58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_5RgBk458EfCez5hyndgAQQ" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_5RgBl458EfCez5hyndgAQQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5RgBlI58EfCez5hyndgAQQ" width="0" height="100"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_5OETEI58EfCez5hyndgAQQ" type="2007" element="_5ODE8I58EfCez5hyndgAQQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_5OETFY58EfCez5hyndgAQQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_5OETFo58EfCez5hyndgAQQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_kAZbkI9lEfCAT71bsCxpoQ" type="3007" element="_kAMAMI9lEfCAT71bsCxpoQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_kAaCoI9lEfCAT71bsCxpoQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kAaCoY9lEfCAT71bsCxpoQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_5OMO4458EfCez5hyndgAQQ" type="3002" element="_5OLn0I58EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5OMO5Y58EfCez5hyndgAQQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5OMO5o58EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5OMO5I58EfCez5hyndgAQQ" x="70" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5OwPkI58EfCez5hyndgAQQ" type="3008" element="_5OvogI58EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5OwPko58EfCez5hyndgAQQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5OwPk458EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5OwPkY58EfCez5hyndgAQQ" x="722" y="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5PkH4I58EfCez5hyndgAQQ" type="3003" element="_5Pjg0I58EfCez5hyndgAQQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5PkH4o58EfCez5hyndgAQQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5PkH4458EfCez5hyndgAQQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5PkH4Y58EfCez5hyndgAQQ" x="1316" y="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yPC2AI59EfCez5hyndgAQQ" type="3005" element="_yPBn4I59EfCez5hyndgAQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yPC2Ao59EfCez5hyndgAQQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yPC2AY59EfCez5hyndgAQQ" x="830" y="293" width="134" height="67"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D6YPXI5-EfCez5hyndgAQQ" type="3005" element="_D6XoQI5-EfCez5hyndgAQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D6YPXo5-EfCez5hyndgAQQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D6YPXY5-EfCez5hyndgAQQ" x="130" y="90" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Jg5y_I5-EfCez5hyndgAQQ" type="3005" element="_Jg5L4I5-EfCez5hyndgAQQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Jg6aAI5-EfCez5hyndgAQQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jg5y_Y5-EfCez5hyndgAQQ" x="379" y="191" width="165" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Jk4W8MTXEfCLWsvb-f-qjg" type="3027" element="_JkqUgMTXEfCLWsvb-f-qjg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Jk4W8sTXEfCLWsvb-f-qjg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Jk4W8cTXEfCLWsvb-f-qjg" x="144" y="246" width="165" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6VY_mcY3EfCAQPVkCXfpoQ" type="3027" element="_6VY_kMY3EfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6VZmoMY3EfCAQPVkCXfpoQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6VY_msY3EfCAQPVkCXfpoQ" x="874" y="56" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ScoFUMY4EfCAQPVkCXfpoQ" type="3005" element="_ScneQMY4EfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ScoFUsY4EfCAQPVkCXfpoQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ScoFUcY4EfCAQPVkCXfpoQ" x="1052" y="291" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b_cfY8Y4EfCAQPVkCXfpoQ" type="3008" element="_b_b4UMY4EfCAQPVkCXfpoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_b_dGcMY4EfCAQPVkCXfpoQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_b_dGccY4EfCAQPVkCXfpoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b_cfZMY4EfCAQPVkCXfpoQ" x="1124" y="191"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_3PAoDMY4EfCAQPVkCXfpoQ" type="3005" element="_3PAA8MY4EfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_3PAoDsY4EfCAQPVkCXfpoQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3PAoDcY4EfCAQPVkCXfpoQ" x="1096" y="67" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hynF8MY6EfCAQPVkCXfpoQ" type="3008" element="_hyl30MY6EfCAQPVkCXfpoQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hynF8sY6EfCAQPVkCXfpoQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hynF88Y6EfCAQPVkCXfpoQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hynF8cY6EfCAQPVkCXfpoQ" x="618" y="215"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wYgYUMY6EfCAQPVkCXfpoQ" type="3027" element="_wYfKMMY6EfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wYgYUsY6EfCAQPVkCXfpoQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wYgYUcY6EfCAQPVkCXfpoQ" x="524" y="47" width="124" height="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kAZbkY9lEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kAZbko9lEfCAT71bsCxpoQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kAZbk49lEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kAaCoo9lEfCAT71bsCxpoQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kAZblI9lEfCAT71bsCxpoQ"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_nYEiAI9lEfCAT71bsCxpoQ" type="3007" element="_nYD68I9lEfCAT71bsCxpoQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_nYFJEI9lEfCAT71bsCxpoQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nYFJEY9lEfCAT71bsCxpoQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_G9NjwI9mEfCAT71bsCxpoQ" type="3005" element="_G9M8yY9mEfCAT71bsCxpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_G9NjwY9mEfCAT71bsCxpoQ" type="5005" element="_G9M8yY9mEfCAT71bsCxpoQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_G9Njwo9mEfCAT71bsCxpoQ" x="130" y="76" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mF_uGMY3EfCAQPVkCXfpoQ" type="3027" element="_mF_HAMY3EfCAQPVkCXfpoQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mF_uGsY3EfCAQPVkCXfpoQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mF_uGcY3EfCAQPVkCXfpoQ" x="394" y="79" width="150" height="75"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nYEiAY9lEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nYEiAo9lEfCAT71bsCxpoQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nYEiA49lEfCAT71bsCxpoQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nYFJEo9lEfCAT71bsCxpoQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nYEiBI9lEfCAT71bsCxpoQ" x="53" y="420" width="1860" height="310"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_5OETEY58EfCez5hyndgAQQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_5OETEo58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_5OETE458EfCez5hyndgAQQ" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_5OETF458EfCez5hyndgAQQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5OETFI58EfCez5hyndgAQQ" width="1438" height="420"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_5NtGso58EfCez5hyndgAQQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_5RvSII58EfCez5hyndgAQQ" type="4001" element="_5RurEI58EfCez5hyndgAQQ" source="_5RnWUI58EfCez5hyndgAQQ" target="_5Rrnw458EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_5RvSI458EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5RvSJI58EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5RvSIY58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5RvSIo58EfCez5hyndgAQQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5Rzjk458EfCez5hyndgAQQ" type="4001" element="_5RzjkI58EfCez5hyndgAQQ" source="_5OMO4458EfCez5hyndgAQQ" target="_D6YPXI5-EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_5Rzjlo58EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5Rzjl458EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5RzjlI58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5RzjlY58EfCez5hyndgAQQ" points="[0, 0, -24, 0]$[24, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5SSEsI58EfCez5hyndgAQQ" type="4001" element="_5SRdoI58EfCez5hyndgAQQ" source="_Jg5y_I5-EfCez5hyndgAQQ" target="_hynF8MY6EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_5SSEs458EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5SSEtI58EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5SSEsY58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5SSEso58EfCez5hyndgAQQ" points="[83, -23, -136, 14]$[211, -23, -8, 14]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_b9obwMD5EfC997thP10FkQ" id="(0.023255813953488372,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5SW9MI58EfCez5hyndgAQQ" type="4001" element="_5SWWII58EfCez5hyndgAQQ" source="_5OwPkI58EfCez5hyndgAQQ" target="_6VY_mcY3EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_5SW9M458EfCez5hyndgAQQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5SW9NI58EfCez5hyndgAQQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5SW9MY58EfCez5hyndgAQQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5SW9Mo58EfCez5hyndgAQQ" points="[0, 0, -24, 0]$[24, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1EsqEI9lEfCAT71bsCxpoQ" type="4001" element="_1Eq04I9lEfCAT71bsCxpoQ" source="_6VY_mcY3EfCAQPVkCXfpoQ" target="_yPC2AI59EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1EsqE49lEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1EsqFI9lEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1EsqEY9lEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1EsqEo9lEfCAT71bsCxpoQ" points="[-30, 42, 143, -238]$[-240, 280, -67, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1EufQI9lEfCAT71bsCxpoQ" id="(1.0,0.4166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FA4Z8Y9mEfCAT71bsCxpoQ" type="4001" element="_FA3y4I9mEfCAT71bsCxpoQ" source="_Jk4W8MTXEfCLWsvb-f-qjg" target="_G9NjwI9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FA5BAI9mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FA5BAY9mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FA4Z8o9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FA4Z849mEfCAT71bsCxpoQ" points="[81, 15, 210, -258]$[81, 46, 210, -227]$[-125, 46, 4, -227]$[-125, 264, 4, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FA6PII9mEfCAT71bsCxpoQ" id="(0.030303030303030304,0.8148148148148148)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FA6PIY9mEfCAT71bsCxpoQ" id="(0.54,0.18)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_G9OK049mEfCAT71bsCxpoQ" type="4001" element="_G9OK0I9mEfCAT71bsCxpoQ" source="_G9NjwI9mEfCAT71bsCxpoQ" target="_mF_uGMY3EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_G9OK1I9mEfCAT71bsCxpoQ" type="6001" element="_G9OK0I9mEfCAT71bsCxpoQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_G9OK1Y9mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_G9OK1o9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_G9OK149mEfCAT71bsCxpoQ" points="[0, 0, -20, 0]$[20, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6eJQwMYoEfCAQPVkCXfpoQ" id="(0.03333333333333333,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_T7lesI9mEfCAT71bsCxpoQ" type="4001" element="_T7h0UI9mEfCAT71bsCxpoQ" source="_5OwPkI58EfCez5hyndgAQQ" target="_G9NjwI9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_T7mFwI9mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_T7mFwY9mEfCAT71bsCxpoQ" x="-89" y="495"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_T7lesY9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_T7leso9mEfCAT71bsCxpoQ" points="[0, 5, 591, -411]$[0, 569, 591, 153]$[-611, 569, -20, 153]$[-611, 439, -20, 23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_T7ms0I9mEfCAT71bsCxpoQ" id="(0.5116279069767442,0.8604651162790697)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_T7ms0Y9mEfCAT71bsCxpoQ" id="(0.23,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZqRf049mEfCAT71bsCxpoQ" type="4001" element="_ZqRf0I9mEfCAT71bsCxpoQ" source="_ZqQRtY9mEfCAT71bsCxpoQ" target="_ZqQ43I9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZqRf1I9mEfCAT71bsCxpoQ" type="6001" element="_ZqRf0I9mEfCAT71bsCxpoQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZqRf1Y9mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZqRf1o9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZqRf149mEfCAT71bsCxpoQ" points="[-4, -3, -97, 0]$[68, 1, -25, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZqRf2I9mEfCAT71bsCxpoQ" id="(1.0,0.9)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZqRf2Y9mEfCAT71bsCxpoQ" id="(0.17123287671232876,0.6301369863013698)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jWyBY49mEfCAT71bsCxpoQ" type="4001" element="_jWyBYI9mEfCAT71bsCxpoQ" source="_yPC2AI59EfCez5hyndgAQQ" target="_ScoFUMY4EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jWyoco9mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jWyoc49mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jWyocI9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jWyocY9mEfCAT71bsCxpoQ" points="[0, 0, -433, 247]$[434, -262, 1, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jWzPgI9mEfCAT71bsCxpoQ" id="(1.0,0.44776119402985076)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Z5YKwMY4EfCAQPVkCXfpoQ" id="(0.013888888888888888,0.4861111111111111)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kxuVY49mEfCAT71bsCxpoQ" type="4001" element="_kxuVYI9mEfCAT71bsCxpoQ" source="_ZqQ47I9mEfCAT71bsCxpoQ" target="_AHT_tMD6EfC997thP10FkQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kxuVZo9mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kxuVZ49mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kxuVZI9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kxuVZY9mEfCAT71bsCxpoQ" points="[-35, 44, 169, -235]$[-210, 249, -6, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kxvjgI9mEfCAT71bsCxpoQ" id="(1.0,0.3888888888888889)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0NddMMYlEfCAQPVkCXfpoQ" id="(0.16279069767441862,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n9bcY49mEfCAT71bsCxpoQ" type="4001" element="_n9bcYI9mEfCAT71bsCxpoQ" source="_iPtEno9mEfCAT71bsCxpoQ" target="_ZqQ4849mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n9bcZo9mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n9bcZ49mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n9bcZI9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n9bcZY9mEfCAT71bsCxpoQ" points="[0, 0, -334, -6]$[333, 20, -1, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_n9cqgI9mEfCAT71bsCxpoQ" id="(1.0,0.38333333333333336)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8mAp8I9mEfCAT71bsCxpoQ" type="4001" element="_8mAC4I9mEfCAT71bsCxpoQ" source="_D6YPXI5-EfCez5hyndgAQQ" target="_Jk4W8MTXEfCLWsvb-f-qjg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8mAp849mEfCAT71bsCxpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8mAp9I9mEfCAT71bsCxpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8mAp8Y9mEfCAT71bsCxpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8mAp8o9mEfCAT71bsCxpoQ" points="[0, 0, -100, -176]$[86, 179, -14, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8mB4EI9mEfCAT71bsCxpoQ" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8mB4EY9mEfCAT71bsCxpoQ" id="(0.14,0.7)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GEVXwMD6EfC997thP10FkQ" type="4001" element="_GERGUMD6EfC997thP10FkQ" source="_AHT_tMD6EfC997thP10FkQ" target="_NQj40MYnEfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GEV-0MD6EfC997thP10FkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GEV-0cD6EfC997thP10FkQ" x="18" y="15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GEVXwcD6EfC997thP10FkQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GEVXwsD6EfC997thP10FkQ" points="[-7, 10, 207, -161]$[-7, 154, 207, -17]$[-2, 154, 212, -17]$[-2, 163, 212, -8]$[-199, 163, 15, -8]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GEXM8MD6EfC997thP10FkQ" id="(0.8837209302325582,0.5348837209302325)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GEXM8cD6EfC997thP10FkQ" id="(0.85,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Unmz8MD6EfC997thP10FkQ" type="4001" element="_UngGQMD6EfC997thP10FkQ" source="_AHT_tMD6EfC997thP10FkQ" target="_NZiDsMD6EfC997thP10FkQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UnnbAMD6EfC997thP10FkQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UnnbAcD6EfC997thP10FkQ" x="-15" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Unmz8cD6EfC997thP10FkQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Unmz8sD6EfC997thP10FkQ" points="[-4, -12, 22, 71]$[-28, -81, -2, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UnoCEMD6EfC997thP10FkQ" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UnoCEcD6EfC997thP10FkQ" id="(0.3333333333333333,0.8666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DsunkMYmEfCAQPVkCXfpoQ" type="4001" element="_Dsq9MMYmEfCAQPVkCXfpoQ" source="_8QqeoMYlEfCAQPVkCXfpoQ" target="_ZqQ47I9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DsvOoMYmEfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DsvOocYmEfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DsunkcYmEfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DsunksYmEfCAQPVkCXfpoQ" points="[-22, -29, -91, 7]$[-22, -37, -91, -1]$[66, -37, -3, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DsxD0MYmEfCAQPVkCXfpoQ" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DsxD0cYmEfCAQPVkCXfpoQ" id="(0.020689655172413793,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gV0H4MYmEfCAQPVkCXfpoQ" type="4001" element="_gVtaMMYmEfCAQPVkCXfpoQ" source="_8QqeoMYlEfCAQPVkCXfpoQ" target="_NZiDsMD6EfC997thP10FkQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gV0H48YmEfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gV0H5MYmEfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gV0H4cYmEfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gV0H4sYmEfCAQPVkCXfpoQ" points="[-22, 10, -329, 150]$[302, -143, -5, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gV0u8MYmEfCAQPVkCXfpoQ" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gV1WAMYmEfCAQPVkCXfpoQ" id="(0.2,0.3)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nUg_YMYmEfCAQPVkCXfpoQ" type="4001" element="_nUejIMYmEfCAQPVkCXfpoQ" source="_ZqQ43I9mEfCAT71bsCxpoQ" target="_8QqeoMYlEfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nUg_Y8YmEfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nUg_ZMYmEfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nUg_YcYmEfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nUg_YsYmEfCAQPVkCXfpoQ" points="[0, 0, -63, -13]$[61, 13, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nUiNgMYmEfCAQPVkCXfpoQ" id="(1.0,0.3972602739726027)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nUiNgcYmEfCAQPVkCXfpoQ" id="(0.09302325581395349,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fVPmQMYnEfCAQPVkCXfpoQ" type="4001" element="_fVO_MMYnEfCAQPVkCXfpoQ" source="_NQj40MYnEfCAQPVkCXfpoQ" target="_iPtEno9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fVQNUMYnEfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fVQNUcYnEfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fVPmQcYnEfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fVPmQsYnEfCAQPVkCXfpoQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fVRbcMYnEfCAQPVkCXfpoQ" id="(0.03,0.28)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fVRbccYnEfCAQPVkCXfpoQ" id="(0.28125,0.21875)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_okGvQMY3EfCAQPVkCXfpoQ" type="4001" element="_okGIMMY3EfCAQPVkCXfpoQ" source="_mF_uGMY3EfCAQPVkCXfpoQ" target="_Jg5y_I5-EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_okGvQ8Y3EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_okGvRMY3EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_okGvQcY3EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_okGvQsY3EfCAQPVkCXfpoQ" points="[-3, -29, 29, 344]$[-36, -356, -4, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_okH9YMY3EfCAQPVkCXfpoQ" id="(0.44666666666666666,0.12)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_okIkcMY3EfCAQPVkCXfpoQ" id="(0.4666666666666667,0.7926829268292683)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kCKYosY4EfCAQPVkCXfpoQ" type="4001" element="_kCJxkMY4EfCAQPVkCXfpoQ" source="_ScoFUMY4EfCAQPVkCXfpoQ" target="_b_cfY8Y4EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kCK_sMY4EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kCK_scY4EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kCKYo8Y4EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kCKYpMY4EfCAQPVkCXfpoQ" points="[-48, -33, 3, 79]$[-48, -65, 3, 47]$[-44, -65, 7, 47]$[-44, -97, 7, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kCMN0MY4EfCAQPVkCXfpoQ" id="(1.0,0.4583333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_l25ssMY4EfCAQPVkCXfpoQ" id="(0.3023255813953488,0.8837209302325582)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nyM7wMY4EfCAQPVkCXfpoQ" type="4001" element="_nyMUsMY4EfCAQPVkCXfpoQ" source="_b_cfY8Y4EfCAQPVkCXfpoQ" target="_ScoFUMY4EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nyM7w8Y4EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nyM7xMY4EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nyM7wcY4EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nyM7wsY4EfCAQPVkCXfpoQ" points="[-2, -8, -28, -124]$[53, -8, 27, -124]$[53, 105, 27, -11]$[29, 105, 3, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nyOJ4MY4EfCAQPVkCXfpoQ" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_nyOJ4cY4EfCAQPVkCXfpoQ" id="(0.9791666666666666,0.6527777777777778)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BXLx4MY5EfCAQPVkCXfpoQ" type="4001" element="_BXJVoMY5EfCAQPVkCXfpoQ" source="_b_cfY8Y4EfCAQPVkCXfpoQ" target="_3PAoDMY4EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BXMY8MY5EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BXMY8cY5EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BXLx4cY5EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BXLx4sY5EfCAQPVkCXfpoQ" points="[-3, -11, 23, 94]$[-36, -93, -10, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BXNAAMY5EfCAQPVkCXfpoQ" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BXNAAcY5EfCAQPVkCXfpoQ" id="(0.375,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_kkgbQMY5EfCAQPVkCXfpoQ" type="4001" element="_kkf0MMY5EfCAQPVkCXfpoQ" source="_3PAoDMY4EfCAQPVkCXfpoQ" target="_5PkH4I58EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_kkgbQ8Y5EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_kkgbRMY5EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_kkgbQcY5EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_kkgbQsY5EfCAQPVkCXfpoQ" points="[0, 0, -101, 25]$[100, -25, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kkhpYMY5EfCAQPVkCXfpoQ" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_kkhpYcY5EfCAQPVkCXfpoQ" id="(0.03333333333333333,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lSzPMMY6EfCAQPVkCXfpoQ" type="4001" element="_lSyoIMY6EfCAQPVkCXfpoQ" source="_hynF8MY6EfCAQPVkCXfpoQ" target="_G9NjwI9mEfCAT71bsCxpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lSzPM8Y6EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lSzPNMY6EfCAQPVkCXfpoQ" x="-71" y="352"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lSzPMcY6EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lSzPMsY6EfCAQPVkCXfpoQ" points="[-22, 11, 409, -413]$[-22, 499, 409, 75]$[-441, 499, -10, 75]$[-441, 429, -10, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lS0dUMY6EfCAQPVkCXfpoQ" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lS0dUcY6EfCAQPVkCXfpoQ" id="(0.5617283950617284,0.9382716049382716)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yZZ5EMY6EfCAQPVkCXfpoQ" type="4001" element="_yZVnoMY6EfCAQPVkCXfpoQ" source="_hynF8MY6EfCAQPVkCXfpoQ" target="_wYgYUMY6EfCAQPVkCXfpoQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yZZ5E8Y6EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yZZ5FMY6EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yZZ5EcY6EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yZZ5EsY6EfCAQPVkCXfpoQ" points="[-2, -9, 16, 81]$[-31, -81, -13, 9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yZagIMY6EfCAQPVkCXfpoQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_yZagIcY6EfCAQPVkCXfpoQ" id="(0.27,0.82)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DoATE8Y7EfCAQPVkCXfpoQ" type="4001" element="_DoATEMY7EfCAQPVkCXfpoQ" source="_wYgYUMY6EfCAQPVkCXfpoQ" target="_5OwPkI58EfCez5hyndgAQQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DoA6IMY7EfCAQPVkCXfpoQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DoA6IcY7EfCAQPVkCXfpoQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DoATFMY7EfCAQPVkCXfpoQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DoATFcY7EfCAQPVkCXfpoQ" points="[0, 0, -77, -17]$[75, 17, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DoBhMMY7EfCAQPVkCXfpoQ" id="(1.0,0.45161290322580644)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DoBhMcY7EfCAQPVkCXfpoQ" id="(0.06976744186046512,0.5116279069767442)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
