export const MAX_STAGES = 100; 
export const MAX_REQUESTS_PER_STAGE = 100;

export const ROLES = {
  MIEMBRO: "MEMBER",
  ONG_ORIGINANTE: "ONG COLABORADORA",
  RED_ONG: "RED ONG",
  CONSEJO_DIRECTIVO: "CONSEJO DIRECTIVO",
};